version: '3.3'

services:

  prometheus:
    image: my-prometheus
    volumes:
      - ./conf/prometheus/:/etc/prometheus/
      - prometheus_data:/var/lib/prometheus
    ports:
      - 9090:9090

  node-exporter:
    image: my-node-exporter
    hostname: '{{.Node.ID}}'
    volumes:
      - /proc:/usr/proc
      - /sys:/usr/sys
      - /:/rootfs
    ports:
      - 9100:9100

  alertmanager:
    image: my-alertmanager
    volumes:
      - ./conf/alertmanager/:/etc/alertmanager/
    ports:
      - 9093:9093

  cadvisor:
    image: google/cadvisor
    hostname: '{{.Node.ID}}'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - grafana.config
    ports:
      - 3000:3000

volumes:
    prometheus_data:
    grafana_data:
    mongodb_data:
